language: objective-c
osx_image: xcode7.3
before_install:
- pod repo update
script: xcodebuild -workspace "RealmConverter.xcworkspace" -scheme "RealmConverter" test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
