language: objective-c
osx_image: xcode8
before_install:
- pod repo update --silent
script:
- set -o pipefail && xcodebuild -workspace "RealmConverter.xcworkspace" -scheme "RealmConverter" clean test | xcpretty
- pod lib lint
