language: objective-c
osx_image: xcode8
install:
    - bundle install
    - pod install --repo-update
script:
    - set -o pipefail && xcodebuild -workspace "RealmConverter.xcworkspace" -scheme "RealmConverter" clean test | xcpretty
    - pod lib lint
